name: build-and-test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: paranoid-test
        run: |
          docker-compose ps --all
          if [[ `docker-compose ps --all | tail -n +3 \
            | wc -l` != `docker-compose ps |  grep " Up " \
            | wc -l` ]]; then exit 1; fi
